name: ${rootProject.projectName}
main: ${rootProject.group}.${rootProject.name}.${rootProject.projectName}
version: ${rootProject.version}
description: ${rootProject.description}
api-version: "1.18"
author: Mowstyl
website: https://clanjhoo.com
depend: [MythicMobs, FreeMinecraftModels]
