[plugins]
shadowPlugin = { id = "com.gradleup.shadow", version.ref = "shadowGradlePlugin" }
generatePOMPlugin = { id = "ru.vyarus.java-lib", version.ref = "generatePOMGradlePlugin" }
spotBugsPlugin = { id = "com.github.spotbugs", version.ref = "spotBugsGradlePlugin" }
userdevPlugin = { id = "io.papermc.paperweight.userdev", version.ref = "userdevGradlePlugin" }

[versions]
shadowGradlePlugin = "9.0.0-beta6"
generatePOMGradlePlugin = "3.0.0"
spotBugsGradlePlugin = "6.1.2"
userdevGradlePlugin = "2.0.0-beta.14"

bukkitVersion = "1.21.4-R0.1-SNAPSHOT"
mythicDist = "5.4.1"
fmmVersion = "1.5.0"

[libraries]
spigotmc-spigotapi = { group = "org.spigotmc", name = "spigot-api", version.ref = "bukkitVersion" }
papermc-paperapi = { group = "io.papermc.paper", name = "paper-api", version.ref = "bukkitVersion" }
lumine-mythicdist = { group = "io.lumine", name = "Mythic-Dist", version.ref = "mythicDist" }
magmaguy-fmm = { group = "com.magmaguy", name = "FreeMinecraftModels", version.ref = "fmmVersion" }
